import type { Metadata } from "next";
import { Roboto, Inter } from "next/font/google";
import Header from '@/components/custom/header'
import Footer from '@/components/custom/FooterSection'
import "./globals.css";

export const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "500", "600", "700"],
});

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-Inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nirvana 0 Brokerage trade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} antialiased`}
      >
        
        <Header />

        <main>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
