import type { Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import Header from '@/components/custom/header'
import Footer from '@/components/custom/Footer'
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["800"], variable: "--font-roboto" });

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"], variable: "--font-poppins" })




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} antialiased`}
      >
        
        <Header />

        <main>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
